let baseHotels=[];let hotels=[];let templates=[];let selectedHotel=null;let editingTemplate=null;let editingHotelIndex=null;
const $=id=>document.getElementById(id);const LS={templates:'ihoNotifyTemplatesV1',hotels:'ihoNotifyHotelsV1',logs:'ihoNotifyLogsV1'};
const vars=['{hotel}','{city}','{province}','{type}','{hotelCode}','{mobile}','{username}','{password}','{capacity}'];
function faNum(x){return String(x??'').replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d))}
function esc(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function mobileParts(v){return faNum(v).split(/[;؛،,\s/]+/).map(x=>x.replace(/[^0-9]/g,'')).filter(Boolean)}
function normMobile(v){let n=mobileParts(v)[0]||'';if(/^09\d{9}$/.test(n))return n;if(/^9\d{9}$/.test(n))return '0'+n;if(/^989\d{9}$/.test(n))return '0'+n.slice(2);return ''}
function extractMobiles(v){const seen=new Set();return mobileParts(v).map(n=>/^09\d{9}$/.test(n)?n:/^9\d{9}$/.test(n)?'0'+n:/^989\d{9}$/.test(n)?'0'+n.slice(2):'').filter(Boolean).filter(n=>!seen.has(n)&&seen.add(n))}
function getMobiles(h){let arr=[...extractMobiles(h.reservePhone).map(m=>({m,s:'رزرو'})),...extractMobiles(h.hotelPhone).map(m=>({m,s:'هتل'})),...extractMobiles(h.mobile).map(m=>({m,s:'موبایل'}))];const seen=new Set();return arr.filter(x=>!seen.has(x.m)&&seen.add(x.m))}
function save(key,val){localStorage.setItem(key,JSON.stringify(val))}function load(key,def){try{return JSON.parse(localStorage.getItem(key)||'')||def}catch{return def}}
function setStatus(id,msg,ok=true){$(id).textContent=msg;$(id).className='status '+(ok?'ok':'err')}
function switchView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('pageTitle').textContent={dashboard:'داشبورد',send:'ارسال پیام',templates:'مدیریت قالب‌ها',hotels:'مدیریت هتل‌ها',reports:'گزارش ارسال',settings:'راهنما و تنظیمات'}[id]||'';renderAll()}
function hydrateMessage(t){const h=selectedHotel||{};return (t||'').replaceAll('{hotel}',h.name||'نام هتل').replaceAll('{city}',h.city||'---').replaceAll('{province}',h.province||'---').replaceAll('{type}',h.type||'---').replaceAll('{hotelCode}',h.hotelCode||'---').replaceAll('{capacity}',h.capacity||'---').replaceAll('{mobile}',normMobile($('mobileInput')?.value)||'---').replaceAll('{username}',$('usernameInput')?.value||'---').replaceAll('{password}',$('passwordInput')?.value||'---')}
function currentTemplate(){return templates.find(t=>t.id===$('templateSelect')?.value)||templates[0]}
function applyTemplate(){const t=currentTemplate();if(!t)return;const need=/\{username\}|\{password\}/.test(t.text||'');$('credentialBox').classList.toggle('hidden',!need);$('messageText').value=hydrateMessage(t.text)}
function renderTemplateSelects(){['templateSelect','editTemplateSelect'].forEach(id=>{const el=$(id);if(!el)return;const cur=el.value;el.innerHTML=templates.map(t=>`<option value="${esc(t.id)}">${esc(t.title)}</option>`).join('');if(cur&&templates.some(t=>t.id===cur))el.value=cur});if(!editingTemplate)editingTemplate=templates[0]?.id; if($('editTemplateSelect')) $('editTemplateSelect').value=editingTemplate||'';loadEditTemplate();applyTemplate();}
function renderCities(){const cities=[...new Set(hotels.map(h=>h.city).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fa'));$('cityFilter').innerHTML='<option value="">همه شهرها</option>'+cities.map(c=>`<option>${esc(c)}</option>`).join('')}
function hotelHay(h){return `${h.name} ${h.city} ${h.province} ${h.hotelCode} ${h.type}`.toLowerCase()}
function renderHotelsList(){const q=($('hotelSearch').value||$('globalSearch').value||'').trim().toLowerCase();const city=$('cityFilter').value;const list=hotels.filter(h=>(!q||hotelHay(h).includes(q))&&(!city||h.city===city)).slice(0,160);$('hotelList').innerHTML=list.map(h=>`<div class="hotelItem ${selectedHotel?.hotelCode===h.hotelCode?'active':''}" data-code="${esc(h.hotelCode)}"><div class="hotelName">${esc(h.name)}</div><div class="meta"><span class="pill">${esc(h.city||'-')}</span><span class="pill">کد ${esc(h.hotelCode||'-')}</span><span class="pill">${esc(h.type||'-')}</span><span class="pill">${getMobiles(h).length} موبایل</span></div></div>`).join('')||'<div class="selected empty">نتیجه‌ای پیدا نشد.</div>';document.querySelectorAll('#hotelList .hotelItem').forEach(el=>el.onclick=()=>selectHotel(hotels.find(h=>String(h.hotelCode)===el.dataset.code)))}
function selectHotel(h){selectedHotel=h;$('selectedHotel').classList.remove('empty');$('selectedHotel').innerHTML=`<b>${esc(h.name)}</b><br>شهر: ${esc(h.city||'-')} | کد: ${esc(h.hotelCode||'-')} | نوع: ${esc(h.type||'-')}<br>رزرو: ${esc(h.reservePhone||'-')}<br>تلفن هتل: ${esc(h.hotelPhone||'-')}`;const ms=getMobiles(h);$('mobileSelect').innerHTML=ms.length?'<option value="">انتخاب شماره</option>'+ms.map(x=>`<option value="${x.m}">${x.m} - ${x.s}</option>`).join('')+'<option value="manual">ورود دستی</option>':'<option value="">شماره موبایل پیدا نشد، دستی وارد کنید</option>';if(ms[0]){$('mobileSelect').value=ms[0].m;$('mobileInput').value=ms[0].m}applyTemplate();renderHotelsList()}
function addLog(channel,result){const logs=load(LS.logs,[]);logs.unshift({at:new Date().toLocaleString('fa-IR'),iso:new Date().toISOString(),hotel:selectedHotel?.name||'-',city:selectedHotel?.city||'-',mobile:$('mobileInput').value||'-',channel,result,message:($('messageText')?.value||'').slice(0,180)});save(LS.logs,logs.slice(0,500));renderLogs();renderDashboard()}
function renderLogs(){const logs=load(LS.logs,[]);const compact=logs.slice(0,8).map(l=>`<div class="log"><b>${esc(l.channel)}</b> · ${esc(l.result)}<br>${esc(l.hotel)} | ${esc(l.mobile)}<br>${esc(l.at)}</div>`).join('')||'<div class="selected empty">هنوز لاگی ثبت نشده.</div>';if($('recentLogs'))$('recentLogs').innerHTML=compact;if($('reportsList'))$('reportsList').innerHTML='<div class="reportRow reportHead"><span>زمان</span><span>هتل</span><span>شماره</span><span>کانال</span><span>نتیجه</span></div>'+logs.map(l=>`<div class="reportRow"><span>${esc(l.at)}</span><span>${esc(l.hotel)}</span><span>${esc(l.mobile)}</span><span>${esc(l.channel)}</span><span>${esc(l.result)}</span></div>`).join('')}
function renderDashboard(){const logs=load(LS.logs,[]);$('kpiHotels').textContent=hotels.length.toLocaleString('fa-IR');$('kpiTemplates').textContent=templates.length.toLocaleString('fa-IR');const today=new Date().toLocaleDateString('fa-IR');$('kpiToday').textContent=logs.filter(l=>(l.at||'').startsWith(today)).length.toLocaleString('fa-IR');$('kpiLast').textContent=logs[0]?.channel||'-';$('templateChips').innerHTML=templates.map(t=>`<span>${esc(t.title)}</span>`).join('')}
async function sendSms(){const mobile=normMobile($('mobileInput').value);const message=$('messageText').value.trim();if(!mobile||!message)return setStatus('sendStatus','شماره موبایل یا متن پیام کامل نیست.',false);$('sendSms').disabled=true;setStatus('sendStatus','در حال ارسال...');try{const r=await fetch('/api/send-sms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mobile,message})});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.message||'خطا در ارسال');setStatus('sendStatus','پیامک با موفقیت ارسال شد.');addLog('SMS','ارسال موفق')}catch(e){setStatus('sendStatus',e.message||'خطا در ارسال',false);addLog('SMS','خطا')}finally{$('sendSms').disabled=false}}
function openApp(kind){const mobile=normMobile($('mobileInput').value);const text=$('messageText').value.trim();if(!text)return setStatus('sendStatus','متن پیام خالی است.',false);navigator.clipboard?.writeText(text);const msg=encodeURIComponent(text);let app='',fb='';if(kind==='WhatsApp'){if(!mobile)return setStatus('sendStatus','برای واتساپ شماره موبایل لازم است.',false);app=`whatsapp://send?phone=98${mobile.slice(1)}&text=${msg}`;fb=`https://wa.me/98${mobile.slice(1)}?text=${msg}`}if(kind==='Telegram'){app=`tg://msg?text=${msg}`;fb=`https://t.me/share/url?url=&text=${msg}`}if(kind==='Bale'){app=`bale://share?text=${msg}`;fb=`https://ble.ir/share/url?url=&text=${msg}`}location.href=app;setTimeout(()=>window.open(fb,'_blank'),1200);addLog(kind,'اپ باز شد / متن کپی شد')}
function loadEditTemplate(){const t=templates.find(x=>x.id===($('editTemplateSelect')?.value||editingTemplate));if(!t)return;editingTemplate=t.id;$('editTemplateTitle').value=t.title;$('editTemplateText').value=t.text;renderTemplatePreview()}
function saveTemplate(){const title=$('editTemplateTitle').value.trim();const text=$('editTemplateText').value.trim();if(!title||!text)return setStatus('templateStatus','عنوان و متن قالب الزامی است.',false);let t=templates.find(x=>x.id===editingTemplate);if(!t){t={id:'tpl_'+Date.now(),title,text};templates.unshift(t)}else{t.title=title;t.text=text}save(LS.templates,templates);setStatus('templateStatus','قالب ذخیره شد.');renderTemplateSelects();renderDashboard()}
function newTemplate(){editingTemplate='tpl_'+Date.now();$('editTemplateSelect').value='';$('editTemplateTitle').value='قالب جدید';$('editTemplateText').value='همکار گرامی {hotel}\n\nمتن پیام را اینجا بنویسید.\n\nتیم تأمین ایران‌هتل';renderTemplatePreview()}
function deleteTemplate(){if(!confirm('قالب حذف شود؟'))return;templates=templates.filter(t=>t.id!==editingTemplate);editingTemplate=templates[0]?.id;save(LS.templates,templates);renderTemplateSelects();setStatus('templateStatus','حذف شد.')}
function renderTemplatePreview(){if($('templatePreview'))$('templatePreview').textContent=hydrateMessage($('editTemplateText').value)}
function renderTemplateVars(){$('templateVars').innerHTML=vars.map(v=>`<code data-var="${v}">${v}</code><span>${({hotel:'نام هتل',city:'شهر',province:'استان',type:'نوع هتل',hotelCode:'کد هتل',mobile:'شماره مقصد',username:'نام کاربری',password:'رمز عبور',capacity:'ظرفیت'}[v.slice(1,-1)]||v)}</span>`).join('');document.querySelectorAll('#templateVars code').forEach(c=>c.onclick=()=>{const el=$('editTemplateText');const s=el.selectionStart||el.value.length;el.value=el.value.slice(0,s)+c.dataset.var+el.value.slice(s);el.focus();renderTemplatePreview()})}
function renderHotelManage(){const q=($('hotelManageSearch')?.value||'').trim().toLowerCase();const list=hotels.filter(h=>!q||hotelHay(h).includes(q)).slice(0,100);$('hotelManageList').innerHTML=list.map((h)=>`<div class="hotelItem" data-code="${esc(h.hotelCode)}"><div class="hotelName">${esc(h.name)}</div><div class="meta"><span class="pill">${esc(h.city||'-')}</span><span class="pill">کد ${esc(h.hotelCode||'-')}</span></div></div>`).join('');document.querySelectorAll('#hotelManageList .hotelItem').forEach(el=>el.onclick=()=>loadHotelForm(hotels.findIndex(h=>String(h.hotelCode)===el.dataset.code)))}
function loadHotelForm(i){editingHotelIndex=i;const h=hotels[i]||{};$('hCode').value=h.hotelCode||'';$('hName').value=h.name||'';$('hCity').value=h.city||'';$('hProvince').value=h.province||'';$('hType').value=h.type||'';$('hCapacity').value=h.capacity||'';$('hReserve').value=h.reservePhone||'';$('hPhone').value=h.hotelPhone||''}
function saveHotel(){const h={country:'ایران',hotelCode:$('hCode').value.trim()||Date.now(),name:$('hName').value.trim(),city:$('hCity').value.trim(),province:$('hProvince').value.trim(),type:$('hType').value.trim(),capacity:$('hCapacity').value.trim(),reservePhone:$('hReserve').value.trim(),hotelPhone:$('hPhone').value.trim()};if(!h.name)return setStatus('hotelStatus','نام هتل الزامی است.',false);if(editingHotelIndex==null||editingHotelIndex<0)hotels.unshift(h);else hotels[editingHotelIndex]=h;save(LS.hotels,hotels);setStatus('hotelStatus','هتل ذخیره شد.');renderCities();renderHotelsList();renderHotelManage();renderDashboard()}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportLogs(){const logs=load(LS.logs,[]);const csv='time,hotel,city,mobile,channel,result,message\n'+logs.map(l=>[l.at,l.hotel,l.city,l.mobile,l.channel,l.result,l.message].map(x=>'"'+String(x||'').replaceAll('"','""')+'"').join(',')).join('\n');download('iran-hotel-notify-logs.csv','\ufeff'+csv,'text/csv')}
function renderAll(){renderDashboard();renderHotelsList();renderTemplateSelects();renderHotelManage();renderLogs()}
async function init(){const [h,t]=await Promise.all([fetch('./data/hotels.json').then(r=>r.json()),fetch('./data/templates.json').then(r=>r.json())]);baseHotels=h;hotels=load(LS.hotels,h);templates=load(LS.templates,t);renderCities();renderTemplateVars();renderAll();document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.querySelectorAll('.jump').forEach(b=>b.onclick=()=>switchView(b.dataset.target));$('quickSend').onclick=()=>{if($('globalSearch').value){$('hotelSearch').value=$('globalSearch').value}switchView('send')};$('hotelSearch').oninput=renderHotelsList;$('globalSearch').oninput=()=>{$('hotelSearch').value=$('globalSearch').value;renderHotelsList()};$('cityFilter').onchange=()=>{renderHotelsList()};$('clearHotel').onclick=()=>{$('hotelSearch').value='';$('globalSearch').value='';$('cityFilter').value='';renderHotelsList()};$('mobileSelect').onchange=e=>{if(e.target.value&&e.target.value!=='manual')$('mobileInput').value=e.target.value;applyTemplate()};['mobileInput','templateSelect','usernameInput','passwordInput'].forEach(id=>$(id).addEventListener('input',applyTemplate));$('templateSelect').onchange=applyTemplate;$('sendSms').onclick=sendSms;$('copyMsg').onclick=()=>{navigator.clipboard.writeText($('messageText').value);setStatus('sendStatus','متن کپی شد.')};$('waBtn').onclick=()=>openApp('WhatsApp');$('tgBtn').onclick=()=>openApp('Telegram');$('baleBtn').onclick=()=>openApp('Bale');$('editTemplateSelect').onchange=e=>{editingTemplate=e.target.value;loadEditTemplate()};$('editTemplateText').oninput=renderTemplatePreview;$('editTemplateTitle').oninput=renderTemplatePreview;$('saveTemplate').onclick=saveTemplate;$('newTemplate').onclick=newTemplate;$('deleteTemplate').onclick=deleteTemplate;$('resetTemplates').onclick=()=>{if(confirm('قالب‌ها به حالت اولیه برگردد؟')){templates=t;save(LS.templates,templates);editingTemplate=templates[0].id;renderTemplateSelects();setStatus('templateStatus','بازنشانی شد.')}};$('hotelManageSearch').oninput=renderHotelManage;$('newHotel').onclick=()=>{editingHotelIndex=null;loadHotelForm(-1)};$('saveHotel').onclick=saveHotel;$('deleteHotel').onclick=()=>{if(editingHotelIndex==null||editingHotelIndex<0)return;if(confirm('هتل حذف شود؟')){hotels.splice(editingHotelIndex,1);editingHotelIndex=null;save(LS.hotels,hotels);renderAll();setStatus('hotelStatus','حذف شد.')}};$('exportHotels').onclick=()=>download('hotels-custom.json',JSON.stringify(hotels,null,2),'application/json');$('exportLogs').onclick=exportLogs;$('clearLogs').onclick=()=>{if(confirm('همه لاگ‌ها پاک شود؟')){save(LS.logs,[]);renderLogs();renderDashboard()}}}
init().catch(e=>alert('خطا در بارگذاری: '+e.message));
